# Generated by Django 5.1.6 on 2025-06-17 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldInfo",
            fields=[
                (
                    "file_index",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="地块编号"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=100, unique=True, verbose_name="地块名称"),
                ),
            ],
            options={
                "verbose_name": "地块信息",
                "verbose_name_plural": "地块信息",
                "db_table": "field_info",
                "ordering": ["file_index"],
            },
        ),
        migrations.CreateModel(
            name="IrregularBlock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("point_index", models.IntegerField(verbose_name="序列号")),
                ("gps_time", models.DateField(verbose_name="GPS时间")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                ("x", models.FloatField(verbose_name="X坐标")),
                ("y", models.FloatField(verbose_name="Y坐标")),
                ("velocity", models.FloatField(verbose_name="速度(km/h)")),
                ("yaw", models.FloatField(verbose_name="航向")),
                (
                    "state",
                    models.BooleanField(
                        choices=[(True, "正常"), (False, "异常")], verbose_name="工作状态"
                    ),
                ),
                ("amplitude", models.FloatField(verbose_name="幅度")),
                ("depth", models.IntegerField(verbose_name="深度")),
                ("DepthValue", models.IntegerField(verbose_name="深度标准值")),
                (
                    "field_name",
                    models.ForeignKey(
                        db_column="field_name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_name.fieldinfo",
                        to_field="file_name",
                        verbose_name="地块名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "地块数据表",
                "verbose_name_plural": "地块数据表",
                "db_table": "point_info",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所属单位"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
            },
        ),
    ]
